### ISSUE TITLE
Table view cells randomising

### ISSUE THREAD

**Issue by chrise86** [clearsightstudio/ProMotion#667] opened 2015-04-06 08:36 UTC
When scrolling up and down the table rows randomise.

I'm using the latest version of Redpotion and RubyMotion.

I'm sure I've had this before but can't figure it out. Any ideas?

**Comment by rheoli** [comment] 2015-04-06 09:24
Same problem here. Looks like when the TableCell is reused the "old" content is used instead the new one (set_title is not called). It can be reproduced just be create the basic RedPotion App with a TableScreen (see ad rheoli/TestApp).

**Comment by rheoli** [comment] 2015-04-06 09:53
There is another create_table_cell in RedPotion under lib/project/pro_motion/table.rb which don't calls setup.

**Comment by rheoli** [comment] 2015-04-06 11:48
Made a small patch for RedPotion infinitered/redpotion#73.

**Comment by jamonholmgren** [comment] 2015-04-06 21:22
Does it still happen with latest Github `master` of RedPotion? We just merged in the ProMotion 2.3 requirement. https://github.com/infinitered/redpotion/pull/69

**Comment by rheoli** [comment] 2015-04-06 22:12
Yes, with the RedPotion master it works correctly (it should when the monkey patch is removed).

**Comment by jamonholmgren** [comment] 2015-04-11 04:18
:+1:

**Closed** 2015-04-11 04:18 UTC
