### ISSUE TITLE
setting properties: {backgroundColor: } sets all subview's background colors

### ISSUE THREAD

**Issue by markrickert** [clearsightstudio/ProMotion#589] opened 2015-01-04 20:53 UTC
So I have a standard cell:

```ruby
{
  title: 'Trader Joe\'s Organic black beans',
  properties: {
    backgroundColor: UIColor.colorWithPatternImage(UIImage.imageNamed('stripe'))
  }
}
```

And this is what I get:

![screen shot 2015-01-04 at 2 12 04 pm](https://cloud.githubusercontent.com/assets/139261/5607141/bda9495a-941b-11e4-8d62-85557dbdc2d6.png)

As you can see, it appears to be setting the titleLabel's backgroundColor to the same color... Is this expected behavior?

**Comment by jamonholmgren** [comment] 2015-01-05 17:02
No, definitely not expected behavior. Strange.

**Comment by ryanlntn** [comment] 2015-01-21 23:34
@markrickert @jamonholmgren This appears to be a problem in RubyMotion in general. I spun up a [non-PM app](https://github.com/ryanlntn/rm-issue-tableviewcell) and setting background color on the table view cell applied the same background color to the text label as well.

Do you think it's a bug in RubyMotion or is this just how table view cells work?

**Comment by jamonholmgren** [comment] 2015-01-22 05:33
Interesting:

![](http://clrsight.co/jh/2015-01-21-z26nd.png?+)

Source: http://www.apeth.com/iOSBook/ch21.html

**Comment by jamonholmgren** [comment] 2015-01-22 05:34
So, it's expected behavior. Closing as it's not our problem... :) (LOVE it when I can say that)

**Closed by jamonholmgren** 2015-01-22 05:34 UTC
Labels: wontfix

**Comment by ryanlntn** [comment] 2015-01-22 16:56
@markrickert It looks like we do provide a way to do this in ProMotion by setting your background color in `will_display` on the table view cell. We could potentially add a hook directly in `TableScreen`. Something like `will_display_cell`. Thoughts?

cc @jamonholmgren

**Comment by jamonholmgren** [comment] 2015-05-13 21:49
We need this `will_display_cell` hook.
