### ISSUE TITLE
Searchable Table Screen With Custom Cell Type Uses Different Cell Height

### ISSUE THREAD

**Issue by sxross** [clearsightstudio/ProMotion#627] opened 2015-02-20 18:58 UTC
I have specified a custom cell class:

```

class EventsScreen < PM::TableScreen
  title "Events"
  searchable placeholder: "Search events"
  row_height 62
  stylesheet EventsScreenStylesheet # rmq stuff

  # other stuff

  def table_data

    @events ||= Event.all
    [
      {
        cells: @events.map do |event|
          {
            properties: {
              event_name: event.event_name,
              event_details: date_time_label(event),
              event_attendees: event.number_of_attendees_in_words
            },
            search_text: "#{event.event_name} #{event.event_location}",
            cell_class: EventsCell
          }
        end
      }
    ]
  end
```

When I do the search, it does select the correct cells but it does not construct them using the specified `cell_class`. Instead, it appears to use a default height. Here is an example:

```
(main)> rmq(EventsCell).first.get.frame.inspect
=> "#<CGRect origin=#<CGPoint x=0.0 y=106.0> size=#<CGSize width=320.0 height=62.0>>"
(main)> rmq(EventsCell).last.get.frame.inspect
=> "#<CGRect origin=#<CGPoint x=0.0 y=0.0> size=#<CGSize width=320.0 height=44.0>>"
```

The first cell is one of the original ones allocated at the requested 62 points. The last one was incorrectly allocated at 44 points.

**Comment by jamonholmgren** [comment] 2015-02-20 23:02
@sxross I'm moving this weekend so won't have time to look into this. Hopefully someone else can!

**Comment by sxross** [comment] 2015-02-21 18:52
I pushed a repo of the entire project that caused this issue at https://github.com/sxross/promotion_issue. The project uses RMQ with Promotion. There's definitely something wonky about the way cell heights are being applied -- it looks like they are being auto fit to content in the case where the cell is unfiltered and default iOS height where the cell is filtered. RMQ is a complicating factor, but it's handy enough for me that tracking down the interactions is worthwhile.

**Comment by squidpunch** [comment] 2015-02-21 19:02
Yeah I whipped up quick sample app and could see it reproduced.  Looks like search result is ignoring the height. I'll pull the repo down and see if I can figure out any insights later tonight if I can find some time

**Comment by sxross** [comment] 2015-02-21 19:04
Thanks!

**Comment by squidpunch** [comment] 2015-02-22 15:50
@jamonholmgren @sxross so there are a few things i see when looking into this 

- right now PM uses `UISearchDisplayController` which is deprecated in iOS8
- you can handle what you want with a delegate, and I am going to add a PR to promotion to fix what you are seeing.

@sxross I pushed a PR to show a working fix to your sample repo which will get you by until its in PM directly, but essentially you just need to add

```ruby
def searchDisplayController(controller, didLoadSearchResultsTableView: tableView)
  # hard coding this to what was set above
  #but in PM we'll pull from the same value - I believe
  tableView.rowHeight = 62
end
```

**Closed** 2015-02-23 17:15 UTC
Labels: question
